version: "3.9"
services:
  web:
    image: edyan/php:7.4-sqlsrv
    container_name: projet-php7.4-apache
    ports:
      - "9300:9300"
    build: './build/php'
    volumes:
      - ./app:/var/www/html
  mysql:
    ports:
      - "3307:3306"
    build: './build/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: "super-secret-password"
      MYSQL_DATABASE: "my-wonderful-website"
    volumes:
      - dbData:/var/lib/mysql
volumes:
  app:
  dbData: